## Numpy

### Installing Numpy

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

### Creating a 1D Array

In [3]:
x = np.array([1,2,3])

### Creating a 2D Array


In [5]:
y = np.array([[1,2],[3,4]])

### Creating a 3D array

In [6]:
z = np.array([[[1,2],[3,4]],[[5,6],[8,9]]])

In [7]:
print(x)
print(y)
print(z)

[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [8 9]]]


## Pandas

### Installing Panda

In [8]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ----------- ---------------------------- 3.1/11.0 MB 20.8 MB/s eta 0:00:01
   ----------------- ---------------------- 4.7/11.0 MB 13.1 MB/s eta 0:00:01
   ---------------------- ----------------- 6.3/11.0 MB 11.0 MB/s eta 0:00:01
   ------------------------------ --------- 8.4/11.0 MB 10.8 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 11.6 MB/s  0:00:00

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   --------

In [9]:
import pandas as pd

In [10]:
s = pd.Series([10,20,30,40])
name = "MyNums"
print(f"Pandas Series:\n{s}")
print(f"Type of series: {type(s)}")

Pandas Series:
0    10
1    20
2    30
3    40
dtype: int64
Type of series: <class 'pandas.core.series.Series'>


In [11]:
data = {
    'Name' : ['Alice', 'Bob', 'Charlie', 'David'],
    'Age' : [25,30,35,39],
    'City' : ['New York', 'London', 'Paris', 'New Stuff'],
    'Salary' : [70000,40000,60000,45000]
}
df = pd.DataFrame(data)
print(f"\n Pandas DataFrame: \n{df}")


 Pandas DataFrame: 
      Name  Age       City  Salary
0    Alice   25   New York   70000
1      Bob   30     London   40000
2  Charlie   35      Paris   60000
3    David   39  New Stuff   45000
